name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Сборка Spring приложения
      - name: Build Spring application
        run: |
          cd back
          mvn -B package

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ThisTooShallPass
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get install postgresql-client -y

      - name: Load database schema
        run: |
          PGPASSWORD=1 psql -h localhost -U postgres -d ThisTooShallPass -W 1 -f ./back/script.sql -W 1

      # Запуск unit тестов Java
      - name: Run Java unit tests
        run: |
          cd back
          mvn test
